### ISSUE TITLE
Image format for full scale images is not JPEG

### ISSUE THREAD

**Issue by sakethramanujam** [sakethramanujam/percy-image-downloader#1]
Currently the saving function in the percy class tries saving a `png` image to `jpg/jpeg` which is a terrible mistake and needs to be corrected ASAP.

**Comment by Tathagata-42** [comment]
Hey , I have installed Percy-image-downloader . How to use it after that ?

**Comment by OBITORASU** [comment]
I think in ```percy-image-downloader/percy/percy.py``` adding an ```if else``` statement around ```filename = os.path.join(filepath, f"{_id}.jpg")``` which checks for resolution value and triggers ```filename = os.path.join(filepath, f"{_id}.png")``` for ```resolution = "full"``` should do the job right?

**Comment by sakethramanujam** [comment]
> Hey , I have installed Percy-image-downloader . How to use it after that ?

Please take look at the [README](https://github.com/sakethramanujam/percy-image-downloader/blob/main/README.md)

**Comment by sakethramanujam** [comment]
> I think in `percy-image-downloader/percy/percy.py` adding an `if else` statement around `filename = os.path.join(filepath, f"{_id}.jpg")` which checks for resolution value and triggers `filename = os.path.join(filepath, f"{_id}.png")` for `resolution = "full"` should do the job right?

I'm thinking long term too, if there's a request for filetype conversion in the future, there needs to be a flag/argument to pass in the file extension/file format. I have something in mind and will raise a PR sometime today. 

Once that's done, I will link that PR here

**Comment by OBITORASU** [comment]
Oh ok, I will close my PR then.

**Comment by sakethramanujam** [comment]
okay! Please feel free to comeback and check other issues out.

**Comment by OBITORASU** [comment]
Sure thing :)

**Comment by sakethramanujam** [comment]
@OBITORASU the issue has now been resolved, please pull and let me know if you run into issues

**Comment by OBITORASU** [comment]
I will check this out once I'm free to hop on to my workstation :)
